ZPLUG_LOCAL_HOME=$(brew --prefix)/opt/zplug

eval $(minikube -p minikube docker-env)

export JAVA_HOME=$(/usr/libexec/java_home)

export PATH="$PATH:$HOME/Library/Python/3.9/bin"
export PATH=$HOME/.gem/ruby/2.6.0/bin:$PATH

alias nproc="sysctl -n hw.ncpu"
alias gcc=/usr/local/bin/gcc-11
alias g++=/usr/local/bin/g++-11
alias cc=/usr/local/bin/g++-11
alias CC=/usr/local/bin/g++-11
alias nvim="env CC=/usr/local/bin/gcc-11 nvim"
