#!/bin/bash

source $HOME/.config/zsh/zsh4h.zsh
source $HOME/.config/zsh/env.zsh
source $HOME/.config/zsh/path.zsh
source $HOME/.config/zsh/alias.zsh
source $HOME/.config/zsh/keybindings.zsh

if [ -e "$HOME/.pyenv/.pyenvrc" ]; then
  z4h source $HOME/.pyenv/.pyenvrc
fi

# pnpm
export PNPM_HOME="/Users/chell/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/opt/homebrew/share/google-cloud-sdk/path.zsh.inc' ]; then . '/opt/homebrew/share/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc' ]; then . '/opt/homebrew/share/google-cloud-sdk/completion.zsh.inc'; fi
